---
- name: Ottieni tutti gli indirizzi IP delle interfacce di rete in formato CSV
  hosts: all
  gather_facts: yes
  tasks:
    - name: Inizializza variabile per CSV
      set_fact:
        csv_data: "Hostname,Interfaccia,Indirizzo IPv4\n"

    - name: Aggiungi indirizzi IP delle interfacce alla variabile CSV
      set_fact:
        csv_data: "{{ csv_data }}{{ ansible_hostname }},{{ iface_var.ipv4.address if (iface_var is defined and iface_var.ipv4 is defined) else 'Nessun indirizzo IPv4 assegnato' }}\n"
      loop: "{{ ansible_interfaces }}"
      vars:
        iface_var: "{{ hostvars[inventory_hostname].get('ansible_' + item) }}"

    - name: Stampa il file CSV
      debug:
        msg: "{{ csv_data }}"
