---
- name: Ottieni tutti gli indirizzi IP delle interfacce di rete
  hosts: all
  gather_facts: yes
  tasks:
    - name: Recupera gli indirizzi IP delle interfacce
      debug:
        msg: >
          Hostname: {{ ansible_hostname }} - Indirizzi IP:
          {% for iface in ansible_interfaces %}
            {{ iface }}:
            {% if hostvars[inventory_hostname]['ansible_' + iface] is defined and
                   hostvars[inventory_hostname]['ansible_' + iface].get('ipv4') is defined %}
              {{ hostvars[inventory_hostname]['ansible_' + iface].ipv4.address }}
            {% else %}
              Nessun indirizzo IPv4 assegnato
            {% endif %}
          {% endfor %}

