---
- name: Ottenere indirizzi IP delle interfacce di rete
  hosts: all
  gather_facts: no
  tasks:
    - name: Esegui il comando ip address
      ansible.builtin.command: ip address
      register: ip_output

    - name: Mostra l'output degli indirizzi IP
      ansible.builtin.debug:
        msg: "{{ ip_output.stdout_lines }}"
