---
- name: Get IP addresses from Linux servers
  hosts: all
  gather_facts: true
  tasks:
    - name: Get IP addresses for all interfaces
      ansible.builtin.shell: ip addr show | grep "inet " | awk '{print $2}'
      register: ip_addresses
      changed_when: false

    - name: Get interface details
      ansible.builtin.shell: ip link show
      register: interfaces
      changed_when: false

    - name: Display CSV formatted output
      ansible.builtin.debug:
        msg: |
          hostname,ip_address,interface
          {% for ip in ip_addresses.stdout_lines %}
          {{ inventory_hostname }},{{ ip }},{{ interfaces.stdout_lines[loop.index0] | regex_replace('^[0-9]+: ([^:]+):.*$', '\\1') }}
          {% endfor %}

