---
- name: Store and Print Ansible Facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Store all facts in a custom variable
      set_fact:
        my_facts: "{{ ansible_facts }}"

    - name: Print stored facts
      debug:
        var: my_facts
