---
- name: Print Ansible Facts in JSON format
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print all facts as JSON
      debug:
        msg: "{{ ansible_facts | to_nice_json }}"
    
    - name: Print all facts as YAML
      debug:
        msg: "{{ ansible_facts | to_nice_yaml }}"
