---
- name: Print Ansible Facts using vars lookup
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print ansible_hostname fact
      debug:
        msg: "{{ lookup('vars', 'ansible_hostname') }}"
